[project]
name = "odoo-addons-oca-sale-workflow"
version = "18.0.20250226.1"
dependencies = [
    "odoo-addon-sale_automatic_workflow==18.0.*",
    "odoo-addon-sale_automatic_workflow_stock==18.0.*",
    "odoo-addon-sale_cancel_reason==18.0.*",
    "odoo-addon-sale_commercial_partner==18.0.*",
    "odoo-addon-sale_exception==18.0.*",
    "odoo-addon-sale_exception_product_sale_manufactured_for==18.0.*",
    "odoo-addon-sale_force_invoiced==18.0.*",
    "odoo-addon-sale_order_archive==18.0.*",
    "odoo-addon-sale_order_line_date==18.0.*",
    "odoo-addon-sale_order_line_menu==18.0.*",
    "odoo-addon-sale_order_line_price_history==18.0.*",
    "odoo-addon-sale_order_product_availability_inline==18.0.*",
    "odoo-addon-sale_order_type==18.0.*",
    "odoo-addon-sale_partner_selectable_option==18.0.*",
    "odoo-addon-sale_procurement_group_by_line==18.0.*",
    "odoo-addon-sale_sourced_by_line==18.0.*",
    "odoo-addon-sale_stock_cancel_restriction==18.0.*",
    "odoo-addon-sale_stock_line_customer_ref==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
